# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{radiant-enabler-extension}
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jim Gay"]
  s.date = %q{2010-04-26}
  s.description = %q{Post to a Radiant CMS site to enable or disable it.}
  s.email = %q{jim@saturnflyer.com}
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    ".gitignore",
     "README.md",
     "Rakefile",
     "VERSION",
     "app/controllers/admin/enabler_controller.rb",
     "config/routes.rb",
     "cucumber.yml",
     "enabler_extension.rb",
     "features/support/env.rb",
     "features/support/paths.rb",
     "lib/radiant-enabler-extension.rb",
     "lib/tasks/enabler_extension_tasks.rake",
     "radiant-enabler-extension.gemspec",
     "spec/controllers/admin/enabler_controller_spec.rb",
     "spec/controllers/site_controller_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/saturnflyer/radiant-enabler-extension}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Enabler Extension for Radiant CMS}
  s.test_files = [
    "spec/controllers/admin/enabler_controller_spec.rb",
     "spec/controllers/site_controller_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

